config/routes.rb
Restaurant::Application.routes.draw do
  
  devise_for :owners
  root 'welcome#index'
  resources :rests

  match '/contact', to: 'welcome#contact', via: 'get'
  match '/signup', to: 'welcome#signup', via: 'get'

  
  

  

  

end

app/models/owner.rb
class Owner < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rests, dependent: :destroy
  validates :name, :email, presence: true
    
  def owns?(restaurant)
  	restaurant.owner == self
  end

end

app/models/rest.rb
class Rest < ActiveRecord::Base
	belongs_to :owner
	validates :name, :address, presence: true
	validates :name, length: { minimum: 3 }
	validates :name, uniqueness: { case_sensitive: false }
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/rests_controller.rb
class RestsController < ApplicationController
  #before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :destroy]
  #before_action :confirm_ownership, only: [:edit, :update, :destroy]

  def index
     @rests = Rest.all
  end

  def show
    @rest = Rest.find(params[:id])
  end

  def new
     @rest = Rest.new
    
  end

  def create
    # @rest = Rest.new(rest_params)
    
      @rest = current_owner.rests.build(rest_params)
     if @rest.save
      redirect_to root_url, notice: "#{@rest.name} was successfully created!"
     else
        render'new'
      end  
     #redirect_to @rest
  end

  def edit
    @rest = Rest.find(params[:id])
  end

  def update
    @rest = Rest.find(params[:id])
 
    #if @rest.update(params[:rest].permit(:name, :description, :address))
       if @rest.update(rest_params)
          redirect_to @rest
        else
          render 'edit'
    end
  end

  def destroy
    @rest = Rest.find(params[:id])
    @rest.destroy
    redirect_to root_url, alert: "#{@rest.name} was successfully deleted!"
  end

  private

  def rest_params
    params.require(:rest).permit(:name, :description, :address, :phone_number, :image)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rests_helper.rb
module RestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a><%= link_to "NYC Restaurants", root_path %></a>
    by Ari Sharon
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "NYC Restaurants", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
         <!-- <li><%#= link_to "Home",    '#' %></li>
          <li><%#= link_to "Help",    '#' %></li> -->
          <% if owner_signed_in? %>
          <p id = "signin" > Signed in as <%= current_owner.email %> </p>
          <%= link_to "Sign out", destroy_owner_session_path, :method => :delete %>
          <% else %>
          <%= link_to "Sign up", new_owner_registration_path %> or
          <%= link_to "Sign in", new_owner_session_path %>
          <% end %>
          <li><%#= link_to "Sign in", new_owner_session_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
     <%= render 'layouts/footer' %> 
     <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/owners/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/rests/_form.html.erb
<%= form_for (@rest), :html => {:multipart => true}  do |f|%>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

   <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

   <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>
  
  <p>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
  </p>

  <p>
      <%#= f.label :image %>
      <%#= image_tag @rest.image_url(:thumb) if @rest.image? %>
      <%#= f.file_field :image, class: 'form-control' %>
      <%#= f.hidden_field :image_cache %> 
   </p>
  <p>
     <% logger.debug "rest: #{@rest.attributes.inspect}" %>
    <%= f.submit %>
    <% logger.debug "rest: #{@rest.attributes.inspect}" %>
  </p>
<% end %>
	

app/views/rests/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/rests/edit.html.haml
%h1 Edit #{@rest.name}

= render 'form'

app/views/rests/index.html.erb
<h1>Restaurants</h1>

<% if owner_signed_in? %>
<%= link_to 'Add Restaurant', new_rest_path, class: "btn " %>
<% end %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @rests.each do |rest| %>
  <tr>
    <td><%= rest.name %></td>
    <td><%= rest.description %></td>
    <td><%= link_to 'Show', rest %></td>
  </tr>
  <% end %>


</table>

app/views/rests/new.html.erb
<h1>  Add a New Restaurant </h1>

<%= render 'form' %>

app/views/rests/show.html.erb
<h5>
	<strong>Name:</strong>
	<%= @rest.name %>
</h5>

<p>
	<strong>Description:</strong>
	<%=  @rest.description %>
</p>

<p>
	<strong>Address:</strong>
	<%=  @rest.address %>
</p>

<p>
	<strong>Phone number:</strong>
	<%=  @rest.phone_number %>
</p>

<p>
	<%# if @rest.owner != nil%>
	<% if @rest.owner != nil%>
    	<strong>Owner: </strong>
	   <%= @rest.owner.name %>
	   <% logger.debug "rest: #{@rest.attributes.inspect}" %>
	 <%end%>
</p>

<%#= image_tag @rest.image_url %>
<%= image_tag @rest.image_url(:thumb) if @rest.image? %>

<% if owner_signed_in? %>
	<%if current_owner.owns?(@rest) %>
		<%= link_to 'Edit', edit_rest_path(@rest) %>
		<%= link_to 'Destroy', rest_path(@rest),
					method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
<% end %>
<%= link_to 'Back', rests_path %>                    

app/views/rests/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/welcome/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Me: 
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/welcome/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to NYC Restaurants <h1>

  <%= link_to "Sign up now!", new_owner_session_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Show Restaurants", 'rests', class: "btn btn-large btn-primary" %>
</div>